apiVersion: v1
kind: Secret
metadata:
  name: weather-app-secrets
  namespace: weather-app
type: Opaque
stringData:
  # IMPORTANT: Replace 'your_openweather_api_key_here' with your actual API key
  # Get it from: https://openweathermap.org/api
  openweather-api-key: "8f516ec1175b66290403094bb6b97d96"
  
  # Database credentials
  # IMPORTANT: Change these in production!
  postgres-password: "weatherpass"
  postgres-user: "weatheruser"
  postgres-db: "weatherdb"
