apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: weather-app
spec:
  accessModes:
    - ReadWriteOnce  # Only one pod can mount this volume at a time
  resources:
    requests:
      storage: 1Gi  # Request 1GB of storage
  # storageClassName: standard  # Uncomment if you want to specify storage class
